long_name = "mod-descriptions 正體中文化"
short_name = "mod-descriptions-zh"
for_module = "tome"
version = {1,7,6}
addon_version = {1,0,0}
weight = 1000000
author = {'tome4-ch'}
homepage = '-'
description = [[mod-descriptions 的正體中文翻譯（非侵入式 locale patch）。]]
tags = {'translate'}
data = true
