-- Verdant Class Pack 正體中文化
-- 非侵入式 locale patch，翻譯 addon "verdant" 的玩家可見字串。
-- 內容規則見 ~/repo/moddings/tome4/sub_proj/zh_mods/GUIDE.md

locale "zh_hant"

section "data-verdant/talents/talents.lua"

t("land", "大地", "talent type")
t("Guide the restless earth.", "引導躁動不安的大地。", "_t")
t("minerals", "礦物", "talent type")
t("Release the natural power of crystals.", "釋放水晶蘊含的自然力量。", "_t")
t("volcanism", "火山", "talent type")
t("Destructive forces for creation renew.", "毀滅之力亦是重生的契機。", "_t")
t("seas", "海洋", "talent type")
t("Rise and fall with the tides.", "隨潮汐起落。", "_t")
t("winds", "風", "talent type")
t("Funnel winds to your aid.", "引導風勢助你一臂之力。", "_t")
t("boreal", "極寒", "talent type")
t("Nature in the frozen lands is harsh and unforgiving.", "極寒之地的自然嚴酷而不留情面。", "_t")
t("weather", "天候", "talent type")
t("Change the weather and use it to your advantage.", "改變天候，並將其化為己用。", "_t")
t("woodland", "林地", "talent type")
t("Grow and animate woodland plants.", "培育並喚醒林地中的植物。", "_t")
t("jungle", "叢林", "talent type")
t("Grow and animate jungle plants.", "培育並喚醒叢林中的植物。", "_t")
t("natural cycles", "自然循環", "talent type")
t("There is a time for everything.", "萬物皆有其時。", "_t")
t("eyals-embrace", "伊亞爾的擁抱", "talent type")
t("Embrace nature, and be embraced back.", "擁抱自然，也被自然擁抱。", "_t")
t("herbalism", "草藥學", "talent type")
t("How to use herbs while on Adventures.", "在冒險途中運用藥草的知識。", "_t")
t("silent hunter", "隱秘獵手", "talent type")
t("You can move without being noticed.", "你能在不被察覺的情況下行動。", "_t")
t("psiclaws", "靈爪", "talent type")
t("Create sharp claws from pure hatred.", "純粹的憎恨化為銳利的爪。", "_t")
t("wolf aspect", "狼形態", "talent type")
t("You are cursed with aspects of a wolf.", "你被詛咒擁有狼的形態。", "_t")
t("ritch aspect", "裏奇形態", "talent type")
t("You are cursed with aspects of a ritch.", "你被詛咒擁有裏奇的形態。", "_t")
t("treant aspect", "樹人形態", "talent type")
t("You are cursed with aspects of a tree.", "你被詛咒擁有樹木的形態。", "_t")
t("eagle aspect", "鷹形態", "talent type")
t("You are cursed with aspects of an eagle.", "你被詛咒擁有鷹的形態。", "_t")
t("shark aspect", "鯊魚形態", "talent type")
t("You are cursed with aspects of a shark.", "你被詛咒擁有鯊魚的形態。", "_t")
t("tiger aspect", "虎形態", "talent type")
t("You are cursed with aspects of a tiger.", "你被詛咒擁有虎的形態。", "_t")
t("bear aspect", "熊形態", "talent type")
t("You are cursed with aspects of a bear.", "你被詛咒擁有熊的形態。", "_t")
t("croc aspect", "鱷魚形態", "talent type")
t("You are cursed with aspects of a crocadile.", "你被詛咒擁有鱷魚的形態。", "_t")
t("fungus aspect", "真菌形態", "talent type")
t("You are cursed with aspects of a fungus.", "你被詛咒擁有真菌的形態。", "_t")
t("snake aspect", "蛇形態", "talent type")
t("You are cursed with aspects of a snake.", "你被詛咒擁有蛇的形態。", "_t")
t("sea drake aspect", "海龍形態", "talent type")
t("Take on the defining aspects of a Sea Drake.", "化身成為海龍形態使你能使用海龍技能。", "_t")
t("wind drake aspect", "風龍形態", "talent type")
t("Take on the defining aspects of a Wind Drake.", "化身成為風龍形態使你能使用風龍技能。", "_t")
t("hunter", "獵人", "talent type")
t("Live your life in the wilds, hunting for your next meal.", "在荒野中討生活，獵取你的下一餐。", "_t")
t("symbiant", "共生體", "talent type")
t("Grow a symbiotic relationship with a jelly.", "與果凍怪培養出共生關係。", "_t")
t("wild drake aspect", "野龍形態", "talent type")
t("Take on the defining aspects of a Wild Drake.", "化身成為野龍形態使你能使用野龍技能。", "_t")
t("blink drake aspect", "瞬龍形態", "talent type")
t("Take on the defining aspects of a Blink Drake. WARNING: These talents are Spells!", "化身成為瞬龍形態使你能使用瞬龍技能。警告：這些天賦屬於法術！", "_t")
t("blood drake aspect", "血龍形態", "talent type")
t("Take on the defining aspects of a Blood Drake. WARNING: These talents are Spells!", "化身成為血龍形態使你能使用血龍技能。警告：這些天賦屬於法術！", "_t")
t("woodcraft", "林務技藝", "talent type")
t("Knowledge of the ways of the wilds.", "關於荒野生存之道的知識。", "_t")
t("bow flexibility", "弓術靈活", "talent type")
t("Techniques to remain flexible while using a bow.", "使用弓箭時保持靈活的技巧。", "_t")
t("summon-techniques", "召喚技巧", "talent type")
t("Techniques for supporting yourself and your summoned creatures.", "支援自身與召喚生物的技巧。", "_t")
t("summon-commands", "召喚指揮", "talent type")
t("Command your summoned creatures to attack and defend.", "指揮你召喚的生物進行攻擊與防禦。", "_t")

------------------------------------------------
section "data-verdant/hooks/load.lua"

t("You should stay away from those fanatics.", "你應該遠離那些狂熱份子。", "log")
t("Somehow as magic user you feel this place is not safe for you.", "不知為何，身為魔法使用者的你覺得這個地方對你並不安全。", "_t")
t("Hmph a Druid. We do not approve of your kind, but nor will we harm a fellow servant of Nature.\nYou passed our test, but the prize would cripple you. Wait a moment, and I will return with something more fitting.\n#LIGHT_GREEN#*he leaves and returns a moment later.*#WHITE#\nTake this rune, a product of our experiments, now leave this place forever.", "哼，一個德魯伊。我們不認同你的同類，但也不會傷害同樣侍奉自然的人。\n你通過了我們的考驗，但這份獎賞對你來說反倒是種負擔。稍等片刻，我會帶著更合適的東西回來。\n#LIGHT_GREEN#*他離開了，片刻後又回來。*#WHITE#\n拿著這枚符文吧，這是我們實驗的產物，然後永遠離開這裡。", "_t")
t("Thank you. I shall not return. #LIGHT_GREEN#[you leave Zigur quickly]", "謝謝，我不會再回來了。#LIGHT_GREEN#[你迅速離開了齊格爾]", "_t")
t("Excellent! You truly prove that no mage-wrought flame or storm can stand against blade and arrow! Come, learn our ways. You are...\n\t\nWait a minute, I sense Magic about you! How did you beat our test with Magic?!", "太好了！你確實證明了沒有任何法師鍛造的烈焰或風暴能擋住刀劍與弓箭！來吧，學習我們的方式。你是……\n\n等等，我察覺到你身上有魔法的氣息！你究竟是如何用魔法通過我們的考驗的？！", "_t")
t("I use Magic in the name of Nature.", "我是以自然之名使用魔法。", "_t")
t("I am ready", "我準備好了", "_t")
t("I need to prepare.", "我還需要準備。", "_t")
t("The antimagic wards seems conflicted for a moment, but then allow your magic.", "反魔法結界似乎猶豫了片刻，但隨後便放行了你的魔法。", "log")
t("Thank you! You have saved many people today!\nI have heard of rumours of a reclusive town of wise and powerful men somewhere in the mountains. Maybe they could help? If they even exist...\nThere are also those Zigur-something people that claim to fight magic. Why are they not here?!", "謝謝你！你今天拯救了許多人！\n我聽說山裡有個隱世的小鎮，住著睿智而強大的人們。或許他們能幫上忙？如果他們真的存在的話……\n還有那些自稱能對抗魔法的齊格爾之類的人，他們怎麼沒出現？！", "_t")
t("I will not let you down.", "我不會讓你失望的。", "_t")
t("So have I heard, @playername@. You prove worthy of your training. Go with the blessing of nature, @playername@ of Zigur.\n#LIGHT_GREEN#*She touches your skin.  You can feel nature infusing your very being.*#WHITE#\nThis shall help your on your travels. Farewell!", "我也聽說了，@playername@。你證明了自己不負這身訓練。帶著自然的祝福上路吧，齊格爾的@playername@。\n#LIGHT_GREEN#*她觸碰你的肌膚，你能感受到自然之力注入你的全身。*#WHITE#\n願這份祝福助你踏上旅途。再會！", "_t")
t("Thank you, Protector.", "謝謝你，守護者。", "_t")
t("#00FF00#You gain the fungus talents school and your Mana Clash is enhanced.", "#00FF00#你獲得了真菌技能樹，你的法力衝擊也得到了強化。", "log")
t("#00FF00#You can now learn new Wild Drake Aspect talents.", "#00FF00#你現在可以學習新的野龍形態天賦了。", "log")
t("When used in a prism:", "當用於稜鏡時：", "_t")
t("Prism damage +%d%%", "稜鏡傷害 +%d%%", "tformat")
t("Prism beam range +%d", "稜鏡光束射程 +%d", "tformat")
t("Equilibrium reduced %d", "失衡值降低 %d", "tformat")
t("%d%% chance to daze for %d turns", "%d%% 機率使目標暈眩 %d 回合", "tformat")
t("%d%% chance to stun for %d turns", "%d%% 機率使目標昏迷 %d 回合", "tformat")
t("Additional %d %s damage", "額外造成 %d 點%s傷害", "tformat")
t("Life regen %d%% of max life", "生命回復提升最大生命值的 %d%%", "tformat")
t("Replaces a few Wyrmic talents with new ones.", "以新天賦取代部分龍戰士天賦。", "_t")
t("#GREEN##{bold}#Verdant: Alter vanilla Wyrmic talents?#WHITE##{normal}#", "#GREEN##{bold}#Verdant：修改原版龍戰士天賦？#WHITE##{normal}#", "_t")
t("Alter vanilla Wyrmic talents? #RED#Best not to change this option in the middle of a game.#LAST#", "修改原版龍戰士天賦？#RED#最好不要在遊戲進行到一半時變更此選項。#LAST#", "_t")
t("Change Selection", "變更選項", "_t")
t("Overhauls the Summoner class.", "全面調整召喚師職業。", "_t")
t("#GREEN##{bold}#Verdant: Alter vanilla Summoner?#WHITE##{normal}#", "#GREEN##{bold}#Verdant：修改原版召喚師？#WHITE##{normal}#", "_t")
t("Alter vanilla Summoner? #RED#Best not to change this option in the middle of a game.#LAST#", "修改原版召喚師？#RED#最好不要在遊戲進行到一半時變更此選項。#LAST#", "_t")
t("Allows NPCs to use Verdant talents.", "允許 NPC 使用 Verdant 天賦。", "_t")
t("#GREEN##{bold}#Verdant: NPCs use Verdant talents?#WHITE##{normal}#", "#GREEN##{bold}#Verdant：讓 NPC 使用 Verdant 天賦？#WHITE##{normal}#", "_t")
t("NPCs use Verdant talents?", "讓 NPC 使用 Verdant 天賦？", "_t")
t("Allows Verdant artifacts to drop.", "允許 Verdant 神器掉落。", "_t")
t("#GREEN##{bold}#Verdant: Enable Artifacts?#WHITE##{normal}#", "#GREEN##{bold}#Verdant：啟用神器？#WHITE##{normal}#", "_t")
t("Enable Verdant Artifacts?", "啟用 Verdant 神器？", "_t")
t("Allows extra staff egos and infusion to be created.", "允許生成額外的法杖詞綴與注入物。", "_t")
t("#GREEN##{bold}#Verdant: Enable extra egos and infusions?#WHITE##{normal}#", "#GREEN##{bold}#Verdant：啟用額外詞綴與注入物？#WHITE##{normal}#", "_t")
t("Enable extra egos and infusions?", "啟用額外詞綴與注入物？", "_t")

------------------------------------------------
section "data-verdant/superload/mod/class/interface/Combat.lua"

t("#ORCHID#%s catches the weapon with its claws and disarms the attacker!#LAST#", "#ORCHID#%s用利爪擋下了武器，並繳了攻擊者的械！#LAST#", "logSeen")
